# Generated by Django 2.2.16 on 2022-04-09 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created'], 'verbose_name': 'Коментарий', 'verbose_name_plural': 'Коментарии'},
        ),
    ]
